# Generated by Django 4.2 on 2024-11-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaokeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('fileMp3Name', models.CharField(max_length=200)),
                ('fileMp3', models.FileField(upload_to='activities/')),
                ('textSong', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWordSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True)),
                ('wordsToDisplay', models.CharField(max_length=200)),
                ('imageName', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='keywordsImage/')),
                ('wordSyntetized', models.FileField(upload_to='words/')),
                ('time_word', models.TimeField()),
                ('teachingActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyWordSongs', to='karaokeapi.teachingactivities')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teachingActivities',
            field=models.ManyToManyField(related_name='activities', to='karaokeapi.teachingactivities'),
        ),
    ]
