# Generated by Django 4.2 on 2024-12-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaokeapi', '0002_teachingactivities_keywordsong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsong',
            name='time_word',
            field=models.IntegerField(),
        ),
    ]
