# Generated by Django 4.2 on 2024-12-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaokeapi', '0003_alter_keywordsong_time_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordsong',
            name='wordSyntetized',
        ),
    ]
